chart-dirs:
  - suomitek
chart-repos:
  - suomitek=https://charts.suomitek.com/suomitek
check-version-increment: true
debug: true
remote: origin
validate-chart-schema: true
validate-maintainers: true
validate-yaml: true
