{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "chineseocr.serviceAccountName" . }}
  labels:
{{ include "chineseocr.labels" . | indent 4 }}
{{- end -}}
